// Code generated by gen.py; DO NOT EDIT.

package aot

import (
	"math"

	"github.com/shibukawa/vkmem/internal/aot/vkaot"
	"github.com/shibukawa/vkmem/internal/aot/vkaot/base"
)

var _ = math.Float64bits

// callExport dispatches a wasm export by name. ok is false for unknown names.
func callExport(m *base.Module, name string, a []uint64) (res []uint64, ok bool) {
	switch name {
	case "__wasm_call_ctors":
		if len(a) != 0 {
			panic("aot: __wasm_call_ctors: want 0 args")
		}
		vkaot.WasmCallCtors(m)
		return nil, true
	case "vkmem_main":
		if len(a) != 2 {
			panic("aot: vkmem_main: want 2 args")
		}
		r := vkaot.VkmemMain(m, int32(uint32(a[0])), int32(uint32(a[1])))
		return []uint64{uint64(uint32(r))}, true
	case "malloc":
		if len(a) != 1 {
			panic("aot: malloc: want 1 args")
		}
		r := vkaot.Malloc(m, int32(uint32(a[0])))
		return []uint64{uint64(uint32(r))}, true
	case "__main_argc_argv":
		if len(a) != 2 {
			panic("aot: __main_argc_argv: want 2 args")
		}
		r := vkaot.MainArgcArgv(m, int32(uint32(a[0])), int32(uint32(a[1])))
		return []uint64{uint64(uint32(r))}, true
	case "vkmem_dlopen":
		if len(a) != 2 {
			panic("aot: vkmem_dlopen: want 2 args")
		}
		r := vkaot.VkmemDlopen(m, int32(uint32(a[0])), int32(uint32(a[1])))
		return []uint64{uint64(uint32(r))}, true
	case "vkmem_dlsym":
		if len(a) != 2 {
			panic("aot: vkmem_dlsym: want 2 args")
		}
		r := vkaot.VkmemDlsym(m, int32(uint32(a[0])), int32(uint32(a[1])))
		return []uint64{uint64(uint32(r))}, true
	case "vkmem_dlclose":
		if len(a) != 1 {
			panic("aot: vkmem_dlclose: want 1 args")
		}
		r := vkaot.VkmemDlclose(m, int32(uint32(a[0])))
		return []uint64{uint64(uint32(r))}, true
	case "vkmem_dlerror":
		if len(a) != 0 {
			panic("aot: vkmem_dlerror: want 0 args")
		}
		r := vkaot.VkmemDlerror(m)
		return []uint64{uint64(uint32(r))}, true
	case "vkmem_call_sighandler":
		if len(a) != 2 {
			panic("aot: vkmem_call_sighandler: want 2 args")
		}
		vkaot.VkmemCallSighandler(m, int32(uint32(a[0])), int32(uint32(a[1])))
		return nil, true
	case "__errno_location":
		if len(a) != 0 {
			panic("aot: __errno_location: want 0 args")
		}
		r := vkaot.ErrnoLocation(m)
		return []uint64{uint64(uint32(r))}, true
	case "strerror":
		if len(a) != 1 {
			panic("aot: strerror: want 1 args")
		}
		r := vkaot.Strerror(m, int32(uint32(a[0])))
		return []uint64{uint64(uint32(r))}, true
	case "ntohs":
		if len(a) != 1 {
			panic("aot: ntohs: want 1 args")
		}
		r := vkaot.Ntohs(m, int32(uint32(a[0])))
		return []uint64{uint64(uint32(r))}, true
	case "fflush":
		if len(a) != 1 {
			panic("aot: fflush: want 1 args")
		}
		r := vkaot.Fflush(m, int32(uint32(a[0])))
		return []uint64{uint64(uint32(r))}, true
	case "htons":
		if len(a) != 1 {
			panic("aot: htons: want 1 args")
		}
		r := vkaot.Htons(m, int32(uint32(a[0])))
		return []uint64{uint64(uint32(r))}, true
	case "htonl":
		if len(a) != 1 {
			panic("aot: htonl: want 1 args")
		}
		r := vkaot.Htonl(m, int32(uint32(a[0])))
		return []uint64{uint64(uint32(r))}, true
	case "free":
		if len(a) != 1 {
			panic("aot: free: want 1 args")
		}
		vkaot.Free(m, int32(uint32(a[0])))
		return nil, true
	case "__funcs_on_exit":
		if len(a) != 0 {
			panic("aot: __funcs_on_exit: want 0 args")
		}
		vkaot.FuncsOnExit(m)
		return nil, true
	case "emscripten_builtin_memalign":
		if len(a) != 2 {
			panic("aot: emscripten_builtin_memalign: want 2 args")
		}
		r := vkaot.EmscriptenBuiltinMemalign(m, int32(uint32(a[0])), int32(uint32(a[1])))
		return []uint64{uint64(uint32(r))}, true
	case "_emscripten_timeout":
		if len(a) != 2 {
			panic("aot: _emscripten_timeout: want 2 args")
		}
		vkaot.EmscriptenTimeout(m, int32(uint32(a[0])), math.Float64frombits(a[1]))
		return nil, true
	case "emscripten_stack_init":
		if len(a) != 0 {
			panic("aot: emscripten_stack_init: want 0 args")
		}
		vkaot.EmscriptenStackInit(m)
		return nil, true
	case "emscripten_stack_get_free":
		if len(a) != 0 {
			panic("aot: emscripten_stack_get_free: want 0 args")
		}
		r := vkaot.EmscriptenStackGetFree(m)
		return []uint64{uint64(uint32(r))}, true
	case "emscripten_stack_get_base":
		if len(a) != 0 {
			panic("aot: emscripten_stack_get_base: want 0 args")
		}
		r := vkaot.EmscriptenStackGetBase(m)
		return []uint64{uint64(uint32(r))}, true
	case "emscripten_stack_get_end":
		if len(a) != 0 {
			panic("aot: emscripten_stack_get_end: want 0 args")
		}
		r := vkaot.EmscriptenStackGetEnd(m)
		return []uint64{uint64(uint32(r))}, true
	case "_emscripten_stack_restore":
		if len(a) != 1 {
			panic("aot: _emscripten_stack_restore: want 1 args")
		}
		vkaot.EmscriptenStackRestore(m, int32(uint32(a[0])))
		return nil, true
	case "_emscripten_stack_alloc":
		if len(a) != 1 {
			panic("aot: _emscripten_stack_alloc: want 1 args")
		}
		r := vkaot.EmscriptenStackAlloc(m, int32(uint32(a[0])))
		return []uint64{uint64(uint32(r))}, true
	case "emscripten_stack_get_current":
		if len(a) != 0 {
			panic("aot: emscripten_stack_get_current: want 0 args")
		}
		r := vkaot.EmscriptenStackGetCurrent(m)
		return []uint64{uint64(uint32(r))}, true
	}
	return nil, false
}
