#!/usr/bin/env python3
"""Generate the glue between the wasm2go output (internal/aot/vkaot) and
the engine-agnostic host table (internal/host).

  imports_gen.go  implements vkaot's EnvImports / Wasi_snapshot_preview1Imports
                  by delegating to host.Fn entries looked up by wasm name.
  exports_gen.go  dispatches Call(name, args...) to the generated export funcs.

usage: gen.py <valkey-server.wasm> (run from internal/aot; needs wasm-tools)
"""
import re, subprocess, sys, os

wasm = sys.argv[1]
here = os.path.dirname(os.path.abspath(__file__))
pkgdir = os.path.join(here, 'vkaot')

# ---- wasm import/export names -------------------------------------------
wat = subprocess.run(['wasm-tools', 'print', wasm], capture_output=True, text=True, check=True).stdout
imports = re.findall(r'\(import "([^"]+)" "([^"]+)" \(func ', wat)
exports = re.findall(r'\(export "([^"]+)" \(func ', wat)

# ---- wasm2go name mangling (mirrors internal/codegen/ids.go) --------------
def mangle_id(s):
    return re.sub(r'[^A-Za-z0-9_]', '_', s)

def export_method_name(name):
    parts = name.split('_')
    out = ''
    prev = None
    for i, p in enumerate(parts):
        if p == '':
            continue
        if out and (p.isdigit() or (prev is not None and prev.isdigit())):
            out += '_' + p
        else:
            out += p[0].upper() + p[1:]
        prev = p
    out = mangle_id(out)
    if not out[0].isupper():
        out = 'X' + out
    return out

def import_method_name(name):
    s = mangle_id(name)
    if s[0].isalpha():
        return s[0].upper() + s[1:]
    return 'X' + s

# ---- parse generated Go signatures ---------------------------------------
sig_re = re.compile(r'^func (\w+)\(m \*base\.Module((?:, l\d+ (?:int32|int64|float64|float32))*)\)(?: (int32|int64|float64|float32))? \{', re.M)
gofuncs = {}
for m in sig_re.finditer(open(os.path.join(pkgdir, 'vkaot.go')).read()):
    params = re.findall(r'l\d+ (int32|int64|float64|float32)', m.group(2))
    gofuncs[m.group(1)] = (params, m.group(3))

iface_re = re.compile(r'^type (\w+) interface \{\n(.*?)^\}', re.M | re.S)
meth_re = re.compile(r'^\s*(\w+)\(m \*Module((?:, l\d+ (?:int32|int64|float64|float32))*)\)(?: (int32|int64|float64|float32))?\s*$', re.M)
ifaces = {}
for m in iface_re.finditer(open(os.path.join(pkgdir, 'base', 'base.go')).read()):
    meths = {}
    for mm in meth_re.finditer(m.group(2)):
        meths[mm.group(1)] = (re.findall(r'l\d+ (int32|int64|float64|float32)', mm.group(2)), mm.group(3))
    ifaces[m.group(1)] = meths

def enc(typ, expr):
    return {'int32': f'uint64(uint32({expr}))', 'int64': f'uint64({expr})',
            'float64': f'math.Float64bits({expr})', 'float32': f'uint64(math.Float32bits({expr}))'}[typ]

def dec(typ, expr):
    return {'int32': f'int32(uint32({expr}))', 'int64': f'int64({expr})',
            'float64': f'math.Float64frombits({expr})', 'float32': f'math.Float32frombits(uint32({expr}))'}[typ]

# ---- imports_gen.go ---------------------------------------------------------
out = ['// Code generated by gen.py; DO NOT EDIT.', '', 'package aot', '',
       'import (', '\t"math"', '', '\t"github.com/shibukawa/vkmem/internal/aot/vkaot/base"', ')', '',
       'var _ = math.Float64bits', '']
iface_of_module = {'env': 'EnvImports', 'wasi_snapshot_preview1': 'Wasi_snapshot_preview1Imports'}
seen = set()
for mod, name in imports:
    if (mod, name) in seen:
        continue
    seen.add((mod, name))
    iface = iface_of_module[mod]
    meth = import_method_name(name)
    if meth not in ifaces[iface]:
        sys.exit(f'import {mod}.{name}: method {meth} not found in {iface}')
    params, ret = ifaces[iface][meth]
    var = 'fn_' + mangle_id(mod) + '_' + mangle_id(name)
    out.append(f'var {var} = mustLookup("{mod}", "{name}")')
    plist = ', '.join(f'l{i} {t}' for i, t in enumerate(params))
    if plist:
        plist = ', ' + plist
    args = ', '.join(enc(t, f'l{i}') for i, t in enumerate(params))
    retsig = f' {ret}' if ret else ''
    out.append(f'func (a *imports) {meth}(m *base.Module{plist}){retsig} {{')
    call = f'{var}.Call(a.h, a.mem, []uint64{{{args}}})'
    if ret:
        out.append(f'\treturn {dec(ret, call)}')
    else:
        out.append(f'\t{call}')
    out.append('}')
    out.append('')
out.append(f'var _ base.EnvImports = (*imports)(nil)')
out.append(f'var _ base.Wasi_snapshot_preview1Imports = (*imports)(nil)')
open(os.path.join(here, 'imports_gen.go'), 'w').write('\n'.join(out) + '\n')

# ---- exports_gen.go ---------------------------------------------------------
out = ['// Code generated by gen.py; DO NOT EDIT.', '', 'package aot', '',
       'import (', '\t"math"', '', '\t"github.com/shibukawa/vkmem/internal/aot/vkaot"',
       '\t"github.com/shibukawa/vkmem/internal/aot/vkaot/base"', ')', '',
       'var _ = math.Float64bits', '',
       '// callExport dispatches a wasm export by name. ok is false for unknown names.',
       'func callExport(m *base.Module, name string, a []uint64) (res []uint64, ok bool) {',
       '\tswitch name {']
n = 0
for name in exports:
    go = export_method_name(name)
    if go not in gofuncs:
        # wasm2go suffixes colliding names with the function index; skip those.
        continue
    params, ret = gofuncs[go]
    args = ', '.join(dec(t, f'a[{i}]') for i, t in enumerate(params))
    out.append(f'\tcase "{name}":')
    out.append(f'\t\tif len(a) != {len(params)} {{ panic("aot: {name}: want {len(params)} args") }}')
    if ret:
        out.append(f'\t\tr := vkaot.{go}(m{", " + args if args else ""})')
        out.append(f'\t\treturn []uint64{{{enc(ret, "r")}}}, true')
    else:
        out.append(f'\t\tvkaot.{go}(m{", " + args if args else ""})')
        out.append('\t\treturn nil, true')
    n += 1
out += ['\t}', '\treturn nil, false', '}', '']
open(os.path.join(here, 'exports_gen.go'), 'w').write('\n'.join(out) + '\n')
print(f'imports: {len(seen)}, exports: {n}')
